@INCLUDE = @CMAKE_CURRENT_SOURCE_DIR@/Doxyfile.in
OUTPUT_DIRECTORY       = @CMAKE_CURRENT_BINARY_DIR@/doxygen/
INPUT                  = @CMAKE_CURRENT_SOURCE_DIR@/src/ @CMAKE_CURRENT_SOURCE_DIR@/README.md 
STRIP_FROM_PATH        = @CMAKE_CURRENT_SOURCE_DIR@
EXAMPLE_PATH           = @CMAKE_CURRENT_SOURCE_DIR@/src/examples/